const defects = ['Académique',
'Acerbe',
'Accro (à xx)',
'Agressif(ive)',
'Aigri(e)',
'Amateur(trice)',
'Ambitieux(euse)',
'Amorphe',
'Anxieux(euse)',
'Arbitraire',
'Arriviste',
'Arrogant(e)',
'Asocial(e)',
'Assisté(e)',
'Autoritaire',
'Autorité (manque d’)',
'Avare',
'Bagarreur(euse)',
'Baratineur(euse)',
'Bavard(e)',
'Blasé(e)',
'Blessant(e)',
'Borné(e)',
'Boudeur(euse)',
'Brouillon(ne)',
'Brute',
'Bruyant(e)',
'Cachottier(e)',
'Calculateur(trice)',
'Capricieux(euse)',
'Caricatural(e)',
'Carriériste',
'Cassant(e)',
'Catastrophiste',
'Castrateur(trice)',
'Caustique',
'Censeur(euse)',
'Cérémonieux',
'Chicaneur(euse)',
'Coléreux(euse)',
'Complexé(e)',
'Compliqué(e)',
'Confiance (manque de)',
'Confus(e)',
'Conventionnel(le)',
'Critiqueur(euse)',
'Cruel(le)',
'Débordé(e)',
'Défaitiste',
'Dépensier(e)',
'Désobéissant(e)',
'Désinvolte',
'Distrait(e)',
'Docile',
'Ecoute (manque d’)',
'Égocentrique',
'Égoïste',
'Émotif(ive)',
'Emporté(e)',
'Envahissant(e)',
'Envieux(euse)',
'Étourdi(e)',
'Excessif(ive)',
'Familier(e)',
'Fantasque',
'Fataliste',
'Formaliste',
'Frondeur(euse)',
'Guindé(e)',
'Grossier(e)',
'Hésitant(e)',
'Humiliant(e)',
'Hyperactif(ive)',
'Hypocrite',
'Immature',
'Impatient(e)',
'Imprudent(e)',
'Impulsif(ive)',
'Inaccessible',
'Inattentif(ive)',
'Incompétent(e)',
'Inconstant(e)',
'Inculte',
'Indécis(e)',
'Indépendant(e)',
'Indiscret(e)',
'Individualiste',
'Influençable',
'Insignifiant(e)',
'Insouciant(e)',
'Instable',
'Intéressé(e)',
'Intolérant(e)',
'Intransigeant(e)',
'Introverti(e)',
'Irrespectueux(euse)',
'Irresponsable',
'Jaloux(se)',
'Laxiste',
'Léger(e)',
'Lent(e)',
'Lourd(e)',
'Lunatique',
'Macho',
'Maladroit(e)',
'Mal à l’aise à l’oral',
'Mal à l’aise en groupe',
'Mal à l’aise au téléphone',
'Mal élevé(e)',
'Maniaque',
'Maniéré(e)',
'Manipulateur(trice)',
'Méchant(e)',
'Médiocre',
'Médisant(e)',
'Méfiant(e)',
'Mégalomane',
'Menteur(euse)',
'Méprisant(e)',
'Mesquin(e)',
'Misogyne',
'Mou(olle)',
'Muet(te)',
'Mythomane',
'Naïf(ïve)',
'Négatif(ive)',
'Négligeant(e)',
'Nerveux(euse)',
'Nonchalant(e)',
'Obstiné(e)',
'Obtus(e)',
'Opiniâtre',
'Orgueilleux(euse)',
'Paresseux(euse)',
'Passif(ive)',
'Pédant(e)',
'Pessimiste',
'Peu à l’aise à l’oral',
'Peu à l’aise en langues',
'Peu autonome sur Word',
'Peu résistant au stress',
'Peu xxx (qualité)',
'Peureux(euse)',
'Plaintif(ive)',
'Planqué(e)',
'Pointilleux(euse)',
'Prétentieux(euse)',
'Procrastinateur(euse)',
'Prudent(e)',
'Qui sait tout',
'Raciste',
'Radin(e)',
'Râleur(euse)',
'Rancunier(e)',
'Reconnaissance (besoin de)',
'Renfermé(e)',
'Résigné(e)',
'Rétrograde',
'Revanchard(e)',
'Rêveur(euse)',
'Rigide',
'Ringard(e)',
'Rouspéteur(euse)',
'Routinier(e)',
'Sans gêne',
'Secret(e)',
'Sensible',
'Solitaire',
'Soupçonneux(euse)',
'Sournois(e)',
'Stressé(e)',
'Stupide',
'Superficiel(le)',
'Susceptible',
'Tatillon(ne)',
'Temps (gestion du)',
'Têtu(e)',
'Timide',
'Triste',
'Trop calme',
'Trop curieux(euse)',
'Trop gentil(le)',
'Trop xxx (qualité)',
'Vaniteux(euse)',
'Versatile',
'Vulgaire']

module.exports = defects