const randomArtists = [
'Alicia Keys',
'Hall &amp; Oates',
'Depeche Mode',
'Pretenders',
'Journey',
'OutKast',
'Mariah Carey',
'Pearl Jam',
'LL Cool J',
'Green Day',
'Elvis Costello',
'Beastie Boys',
'Bee Gees',
'George Michael',
'N.W.A.',
'The Band',
'Curtis Mayfield',
'Earth, Wind and Fire',
'Steely Dan',
'ABBA',
'Mary J. Blige',
'Eminem',
'Judas Priest',
'Lynyrd Skynyrd',
'Run-D.M.C.',
'Rush',
'The Cure',
'Van Morrison',
'Janis Joplin',
'R.E.M.',
'Def Leppard',
'2Pac',
'Otis Redding',
'Coldplay',
'Justin Timberlake',
'The Doors',
'Talking Heads',
'Notorious B.I.G.',
'Genesis',
'Cream',
'Whitney Houston',
'Tom Petty &amp; The Heartbreakers',
'Cheap Trick',
'Iggy &amp; The Stooges',
'KISS',
'Peter Gabriel',
'Public Enemy',
'Little Richard',
'Beyoncé',
'Billy Joel',
'Sade',
'Parliament-Funkadelic',
'Rage Against The Machine',
'Jay-Z',
'Ramones',
'Al Green',
'Joni Mitchell',
'Ray Charles',
'Metallica',
'Van Halen',
'The Police',
'The Kinks',
'Sly &amp; The Family Stone',
'Fleetwood Mac',
'Paul McCartney',
'Johnny Cash',
'Tina Turner',
'Guns N’ Roses',
'Black Sabbath',
'John Lennon',
'Aerosmith',
'Radiohead',
'Elton John',
'Aretha Franklin',
'Neil Young',
'Chuck Berry',
'The Velvet Underground',
'AC/DC',
'The Clash',
'Bruce Springsteen',
'Marvin Gaye',
'U2',
'Pink Floyd',
'Queen',
'Madonna',
'The Beach Boys',
'Nirvana',
'The Who',
'David Bowie',
'Bob Marley',
'Stevie Wonder',
'James Brown',
'Elvis Presley',
'Prince',
'Jimi Hendrix',
'Rolling Stones',
'Led Zeppelin',
'Michael Jackson',
'Bob Dylan',
'The Beatles']

module.exports = randomArtists;